### ISSUE TITLE
Lands compatibility bug

### ISSUE THREAD

**Issue by alexey-va** [MinevoltRPG/Trails#11]
When I walk in wilderness the Trails plugin throws this error:

[01:33:54 ERROR]: Could not pass event SignificantPlayerMoveEvent to Trails v1.0
java.lang.NullPointerException: Cannot invoke "me.angeschossen.lands.api.land.Area.hasFlag(java.util.UUID, me.angeschossen.lands.api.flags.types.RoleFlag)" because the return value of "me.ccrama.Trails.compatibility.LandsAPIHook.getArea(org.bukkit.Location)" is null
        at me.ccrama.Trails.compatibility.LandsAPIHook.hasTrailsFlag(LandsAPIHook.java:75) ~[Trails-1.0.jar:?]
        at me.ccrama.Trails.listeners.MoveEventListener.walk(MoveEventListener.java:73) ~[Trails-1.0.jar:?]
        ... the rest is in the log

And also I cant find a trail flag in the role settings. Not sure if it is a bug or I am doing something wrong. When walking on my land it spams: "You cant create trails here" and I dont know how to allow it. 

Amazing idea for a plugin btw, hopefully Lands compatibility will be fixed soon :)

[latest.log](https://github.com/MinevoltRPG/Trails/files/9804977/latest.log)

**Comment by DrkMatr1984** [comment]
Thanks for the bug report! The Lands support was a request by a user. I never actually got to test Lands compatibility as I do not actually own the plugin... I used LandsAPI (A jar just containing the API that angeschossen provides for coders) to code it, and someone else was supposed to test for me, and never replied for the last 4 monthes, so I went ahead and uploaded the update anyway. 
I can try to solve the NPE but that may not actually fix the Lands compatibility :( Hopefully someone can provide me with a copy to test with or maybe I will eventually get around to buying it myself. But it's rather pricey for a plugin I don't intend to use soooo.... *shrugs* 
If you feel comfortable lending me a copy (I'm not sure if it has seller protection or anything built in) or have a test server you feel comfortable lending me access to (like ftp access/file access and ability to restart) I could definitely fix the Lands support in the next week or two.
Again, thanks for the bug report and I hope to get this working soon also! :)

**Comment by alexey-va** [comment]
Sadly, I cant give you FTP access to a server because of some circumstances. And Lands terms of service are very spooky so I kinda dont want so share it. Maybe I can setup a test server, you will send me snapshots of Trails and I will restart server on your request and send you logs. Not very comfortable of course, but thats something

**Comment by DrkMatr1984** [comment]
ok, Well for now I will attempt to fix the NPE and upload a test version here.

**Comment by DrkMatr1984** [comment]
[*This*](https://minevolt.net/downloads/Trails-1.0.jar) should fix the NPE, so it's not so spammy, but I'm not sure if it will fix the Lands support.

**Comment by DrkMatr1984** [comment]
The RoleFlag should be in the action category for roleFlags and should be called "ALLOW_TRAILS". I have never used the plugin so I don't know how you set role flags. Maybe [this](https://github.com/Angeschossen/Lands/wiki/How-to-Start-as-a-Player#toggle-permissions-for-players)? And it looks like in the config you may be able to manually add ALLOW_TRAILS in [here](https://github.com/Angeschossen/Lands/wiki/Roles-and-their-Flags#edit--add-default-roles), which would make all newly claimed plots allow you, the owner, to create trails without having to assign yourself the permission/flag. Also, you can turn off the deny messages in the [config](https://github.com/MinevoltRPG/Trails/blob/caad47c827993a60f9f419bd1409b165674bbe08/src/main/resources/config.yml#L12-L14), or delay how often they are sent by changing the interval setting.

**Comment by alexey-va** [comment]
Trails in wilderness are working fine! Flags are still missing. However I think I found the problem.
landsIntegration.registerFlag(roleFlag); 
Add this at the end of the Lands hook constructor

**Comment by alexey-va** [comment]
Btw, are you sure it is a good idea to loop through all TrailBlocks every time? If I remember correctly there is a thing called persistent data container for each block on the map. Check this out:
https://www.youtube.com/watch?v=8oeZYgkf0Lo&list=PLfu_Bpi_zcDNEKmR82hnbv9UxQ16nUBF7&index=71
You can utilize this to store walks amount :)

**Comment by DrkMatr1984** [comment]
Thanks for the PR! I added the register as well and have updated the Repo.
[I guess give this a try!
](https://minevolt.net/downloads/Trails-1.0.jar)

**Comment by DrkMatr1984** [comment]
If lands compatibility is fixed and the data container PR you sent me is working (I didn't test) I will update on spigot soon and close this Issue.

**Comment by DrkMatr1984** [comment]
Since I didn't get a reply about the Lands bug I will consider it solved. Thanks for everything!
